name: 'Build & Test Pull Requests'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: actions/setup-node@v3
        name: Set up Node
        with:
          node-version: 18.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build everything
        run: yarn build
      - name: Lint everything
        run: yarn lint
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: actions/setup-node@v3
        name: Set up Node
        with:
          cache: yarn
          node-version: 18.x
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run unit tests
        run: yarn test:unit:ci
        id: unit-tests
      - name: Upload unit test tesults
        if: ${{ always() }}
        uses: bojanrajkovic/jest-github-action@a43a5f7f5622e2427dd051f2ee8d1f49f4039f5e
        with:
          check-name: Unit Test Results
          coverage-comment: false
          skip-test-run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload unit test coverage artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: lcov
          path: ${{github.workspace}}/coverage/lcov-unit.info
  codeclimate:
    name: Upload Coverage to CodeClimate
    runs-on: ubuntu-latest
    needs:
      - unit_test
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: lcov
      - name: Upload coverage to CodeClimate
        if: github.actor != 'dependabot[bot]'
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/lcov-unit.info:lcov